name: _docs-deploy (reusable)

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: '3.12'
      install-extras:
        type: string
        default: '.[docs]'
      docs-path:
        type: string
        default: 'docs'
      output-dir:
        type: string
        default: 'docs/_build/html'
      run-apidoc:
        type: boolean
        default: false
      apidoc-args:
        type: string
        default: '-o docs/api src'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history + tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure tags present
        run: git fetch --force --tags --prune

      - name: Setup Python + uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ inputs.python-version }}


      - name: Install project + docs deps (uv)
        if: inputs.use-uv == true
        run: uv sync --frozen ${{ inputs.install-extras }}

      - name: Generate API stubs (optional)
        if: inputs.run-apidoc == true
        run: uv run --frozen sphinx-apidoc ${{ inputs.apidoc-args }}

      - name: Build multiversion HTML
        run: uv run --frozen sphinx-multiversion "${{ inputs.docs-path }}" "${{ inputs.output-dir }}"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.output-dir }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
