name: _docs-ci (reusable)

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version to use
        type: string
        default: '3.12'
      install-extras:
        description: Extra selector to install docs deps (e.g., .[docs])
        type: string
        default: '.[docs]'
      docs-path:
        description: Path to Sphinx docs dir
        type: string
        default: 'docs'
      output-dir:
        description: Where to write built HTML
        type: string
        default: 'docs/_build/html'
      fail-on-warnings:
        description: Treat Sphinx warnings as errors (-W)
        type: boolean
        default: true
      linkcheck:
        description: Run sphinx linkcheck (non-blocking)
        type: boolean
        default: false
      run-apidoc:
        description: Run sphinx-apidoc before build
        type: boolean
        default: false
      apidoc-args:
        description: Args passed to sphinx-apidoc
        type: string
        default: '-o docs/api src'
      artifact-name:
        description: Name for uploaded site artifact
        type: string
        default: 'site'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python + uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install project + docs deps (uv)
        run: uv sync --frozen ${{ inputs.install-extras }}

      - name: Generate API stubs (optional)
        if: inputs.run-apidoc == true
        run: uv run --frozen sphinx-apidoc ${{ inputs.apidoc-args }}

      - name: Ensure autosummary dirs exist (nice logs)
        run: |
          mkdir -p "${{ inputs.docs-path }}/generated" "${{ inputs.docs-path }}/_autosummary" || true

      - name: Build HTML
        run: |
          FLAGS=""
          if [ "${{ inputs.fail-on-warnings }}" = "true" ]; then FLAGS="-W"; fi
          uv run --frozen sphinx-build $FLAGS -b html "${{ inputs.docs-path }}" "${{ inputs.output-dir }}"

      - name: Linkcheck (non-blocking)
        if: inputs.linkcheck == true
        run: uv run --frozen sphinx-build -b linkcheck "${{ inputs.docs-path }}" "${{ inputs.docs-path }}/_build/linkcheck" || true

      - name: Upload built site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.output-dir }}
