# This is NOT a reusable workflow, and is not part of the public API.
#
# This workflow is triggered by a push to a version tag (e.g. v1.2.3) or
# manually via workflow_dispatch. It creates a GitHub release and uploads the
# built artifacts.
# * The concurrency group ensures that only one release job runs at a time.
name: "Release"

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'          # semver tags
  workflow_dispatch:

permissions:
  contents: write    # create release + upload assets

concurrency:
  group: release
  cancel-in-progress: false   # let releases finish

jobs:
  Release:
    runs-on: ubuntu-latest
    # only run on a tag push, or on a manual dispatch *where* the user has
    # selected a tag ref (i.e. github.ref starts with refs/tags/)
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # on push this is already the tag ref; on dispatch you must choose
          # the tag in the UI so github.ref is the tag
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
